version: '3.4'

services:

  transactionalbox.customerregistrations:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=1001
      - ASPNETCORE_HTTPS_PORTS=1000
    ports:
      - "1001"
      - '1000:1000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  transactionalbox.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=2001
      - ASPNETCORE_HTTPS_PORTS=2000
    ports:
      - "2001"
      - '2000:2000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  transactionalbox.bankaccounts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=3001
      - ASPNETCORE_HTTPS_PORTS=3000
    ports:
      - "3001"
      - '3000:3000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  transactionalbox.loans:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=4001
      - ASPNETCORE_HTTPS_PORTS=4000
    ports:
      - "4001"
      - '4000:4000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro