name: Test documentation deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/documentation*.yml'
      - 'documentation/**'

jobs:
  deploy:
  
    name: Test documentation deployment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: ./documentation

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test build website
        run: npm run build