name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:

  build:

    name: Pull request

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-restore --configuration Release